feat(plugin): sticky columns
CrowdStrike/ember-headless-table pull request #4
Opened 2022-10-04 17:01 UTC by NullVoxPopuli

wip

2022-10-11 21:56 UTC, NullVoxPopuli commented on .github/workflows/ci.yml
> +          # - typescript@4.8
clickable: https://github.com/typed-ember/glint/issues/406

2022-10-12 12:57 UTC, nicolechung commented
<img width="1269" alt="Screen Shot 2022-10-12 at 8 55 05 AM" src="https://user-images.githubusercontent.com/771170/195348425-aa95f654-7495-4b90-a896-7606d8dcc690.png">

The "Edit this demo" link currently 404's in the do-it-live link, is this intentional? Like, does it only work in dev mode?

2022-10-13 13:29 UTC, nicolechung approved these changes
A very minor nit: I am not clear by clicking on the demo on what sticky:left/sticky:right does since A is sticking left and G is sticking right.

Maybe if "F" was also sticking left I could see the difference?

2022-10-13 13:59 UTC, NullVoxPopuli commented
Does the code help? 
```
const leftSticky = () => StickyColumns.forColumn(() => ({ sticky: 'left' }));
const rightSticky = () => StickyColumns.forColumn(() => ({ sticky: 'right' }));

export default class extends Component {
  table = headlessTable(this, {
    columns: () => [
      { name: 'column A', key: 'A', pluginOptions: [leftSticky(), ...] },
     // ...
      { name: 'column G', key: 'G', pluginOptions: [rightSticky(), ...] },
```

2022-10-13 14:14 UTC, nicolechung commented
>But in general I want to make all these demos have configurable options -- but I need to invent a UI for that 😅

Ah gotcha. Yeah I def don't think it's a blocker and I can play around with it on localhost in my own time to understand it.

2022-10-13 14:22 UTC, nicolechung requested changes
Question about the `sticky` style attribute instead of a sticky class.

2022-10-13 14:27 UTC, nicolechung approved these changes

2022-10-13 14:29 UTC, merged